//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaRezervasyon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class blgFilm
    {
        public int Id { get; set; }
        public Nullable<int> FilmTabloId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public Nullable<int> SeansId { get; set; }
        public Nullable<int> TurId { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string ResimUrl { get; set; }
    
        public virtual blgFilmTablo blgFilmTablo { get; set; }
        public virtual blgSalon blgSalon { get; set; }
        public virtual blgSean blgSean { get; set; }
        public virtual blgTur blgTur { get; set; }
    }
}
