//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaRezervasyon.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaaDbEntities : DbContext
    {
        public SinemaaDbEntities()
            : base("name=SinemaaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blgFilm> blgFilms { get; set; }
        public virtual DbSet<blgFilmTablo> blgFilmTabloes { get; set; }
        public virtual DbSet<blgIcecek> blgIceceks { get; set; }
        public virtual DbSet<blgKoltuk> blgKoltuks { get; set; }
        public virtual DbSet<blgPersonel> blgPersonels { get; set; }
        public virtual DbSet<blgSalon> blgSalons { get; set; }
        public virtual DbSet<blgSean> blgSeans { get; set; }
        public virtual DbSet<blgTur> blgTurs { get; set; }
        public virtual DbSet<blgYiyecek> blgYiyeceks { get; set; }
        public virtual DbSet<blgYonetici> blgYoneticis { get; set; }
        public virtual DbSet<tblCiro> tblCiroes { get; set; }
        public virtual DbSet<tblSati> tblSatis { get; set; }
    }
}
