//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaRezervasyon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSati
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> TurId { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public Nullable<int> SeansId { get; set; }
        public Nullable<int> YiyecekId { get; set; }
        public Nullable<int> IcecekId { get; set; }
        public Nullable<int> BiletAdet { get; set; }
        public string BiletNo { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> KoltukId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> Tutar { get; set; }
    
        public virtual blgFilmTablo blgFilmTablo { get; set; }
        public virtual blgIcecek blgIcecek { get; set; }
        public virtual blgKoltuk blgKoltuk { get; set; }
        public virtual blgPersonel blgPersonel { get; set; }
        public virtual blgSalon blgSalon { get; set; }
        public virtual blgSean blgSean { get; set; }
        public virtual blgTur blgTur { get; set; }
        public virtual blgYiyecek blgYiyecek { get; set; }
    }
}
